[package]
name = "wasm0x-zkwasmsdk"
version = "0.1.0"
edition = "2021"

[dependencies]
fixed-bigint = "0.1.9"
wee_alloc = "0.4.5"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
lto = true
opt-level = 'z'
strip = true