[package]
name = "hello"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm0x-zkwasmsdk = { path = "../.." }

[lib]
crate-type = ["cdylib"]
# uncomment desired example
#path = "src/lib_evm_address.rs"
path = "src/lib_evm_timestamp.rs"
#path = "src/lib_evm_call_value.rs"
